language: python
python:
  - "3.8"
jobs:
  include:
    - stage: Run unit tests
      script: pytest
    - stage: Build Docker image
      script: docker build -t chrisjhart/travis-test .
    - stage: Push Docker image to DockerHub
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
