language: python
python:
  - "3.8"
jobs:
  include:
    - stage: Run unit tests
      script: pytest
    - stage: Push Docker image to DockerHub
      script: docker build -t chrisjhart/travis-test . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push chrisjhart/travis-test
